language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 4a68925627559a74a9dd846882378b6e0451e598
 local_dir: dist
 on:
   branch: master

